param([switch]$Check)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$dataRoot = Join-Path $repoRoot 'data\categories'
$annales = Get-Content (Join-Path $repoRoot 'data\annales\questions-europeennes-2026.json') -Raw -Encoding UTF8 | ConvertFrom-Json
$questionsById = @{}
foreach ($question in $annales.questions) { $questionsById[$question.id] = $question }
$bundle = [ordered]@{ version_format = '1.0.0'; categories = @(); sources = [ordered]@{}; questions = @() }
$catalogue = [Collections.Generic.List[string]]::new()
$catalogue.Add('# Catalogue des 375 questions par catégorie')
$catalogue.Add('')
$catalogue.Add('Fichier généré par `scripts/sync-categories.ps1`. Les corrigés sont pédagogiques, non officiels. Les questions reprises conservent le contexte temporel de leur sujet. Les lettres renvoient aux choix des fichiers JSON et de la page de quiz.')
$usedIds = @{}
foreach ($categoryId in @('histoire', 'institutions', 'fonctionnement', 'politiques', 'relations')) {
  $category = Get-Content (Join-Path $dataRoot "$categoryId.json") -Raw -Encoding UTF8 | ConvertFrom-Json
  if ($category.id -cne $categoryId) { throw "Identifiant de catégorie invalide : $categoryId" }
  $sourceId = "thematique-$categoryId"
  $bundle.sources[$sourceId] = [ordered]@{
    type = 'thematique'; titre = $category.titre; mode_reponse_qcm = 'une_seule'; date_revision = $category.date_revision
  }
  foreach ($question in $category.questions) {
    if ($questionsById.ContainsKey($question.id)) { throw "Identifiant en double : $($question.id)" }
    if ($question.source.id -cne $sourceId -or $question.correction.reponses.Count -ne 1) { throw "Source ou réponse invalide : $($question.id)" }
    $questionsById[$question.id] = $question
    $bundle.questions += $question
  }
  $ids = @($category.question_ids) + @($category.questions | ForEach-Object { $_.id })
  if ($ids.Count -ne 75) { throw "$categoryId doit contenir exactement 75 questions." }
  $bundle.categories += [ordered]@{ id = $category.id; titre = $category.titre; description = $category.description; question_ids = $ids }
  $catalogue.Add('')
  $catalogue.Add("## $($category.titre)")
  $catalogue.Add('')
  $catalogue.Add("75 questions : $($category.question_ids.Count) reprises et $($category.questions.Count) nouvelles.")
  foreach ($id in $ids) {
    if ($usedIds.ContainsKey($id)) { throw "Question classée plusieurs fois : $id" }
    $usedIds[$id] = $true
    $q = $questionsById[$id]
    if (!$q -or $q.type -ne 'qcm' -or $q.correction.neutralisee -eq $true -or !$q.correction.reponses -or !$q.correction.explication -or !$q.correction.sources) { throw "Question sans corrigé complet : $id" }
    $letters = @($q.choix.PSObject.Properties.Name)
    if ($letters.Count -lt 2 -or @($q.correction.reponses | Select-Object -Unique).Count -ne $q.correction.reponses.Count) { throw "Choix ou correction invalides : $id" }
    foreach ($letter in $q.correction.reponses) {
      if ($letter -cnotin $letters) { throw "Réponse absente des choix : $id" }
    }
    foreach ($reference in $q.correction.sources) {
      if (!$reference.titre -or $reference.url -notmatch '^https://') { throw "Référence invalide : $id" }
    }
    $source = if ($q.source.id -eq $sourceId) { $bundle.sources[$sourceId] } else { $annales.sources.($q.source.id) }
    if (!$source) { throw "Source inconnue : $id" }
    $origin = if ($source.type -eq 'thematique') { "Question originale d’entraînement" } else {
      $title = if ($source.titre) { $source.titre } else { "$($source.code_concours) $($source.annee_concours)" }
      $date = if ($source.date_epreuve) { $source.date_epreuve } else { $source.date_creation_pdf }
      "$title, question $($q.source.numero) ; contexte du sujet : $date"
    }
    $catalogue.Add('')
    $catalogue.Add("### $id")
    $catalogue.Add('')
    $catalogue.Add($q.enonce)
    $catalogue.Add('')
    $catalogue.Add("Provenance : $origin.")
    $catalogue.Add('')
    foreach ($choice in $q.choix.PSObject.Properties) { $catalogue.Add("- $($choice.Name.ToUpper()). $($choice.Value)") }
    $catalogue.Add('')
    $catalogue.Add('**Réponse : ' + (($q.correction.reponses | ForEach-Object { $_.ToUpper() }) -join ', ') + '.** ' + $q.correction.explication)
    $catalogue.Add('')
    $catalogue.Add(($q.correction.sources | ForEach-Object { '[' + $_.titre + '](' + $_.url + ')' }) -join ' · ')
  }
}
$json = ($bundle | ConvertTo-Json -Depth 30).Replace("`r`n", "`n").Replace([string][char]0x2028, '\u2028').Replace([string][char]0x2029, '\u2029')
$outputs = @{
  'questions-europeennes.json' = "$json`n"
  'questions-europeennes.js' = "// Generated by scripts/sync-categories.ps1. Do not edit directly.`nwindow.QcmCategories = $json;`n"
  'CATALOGUE.md' = ($catalogue -join "`n") + "`n"
}
foreach ($entry in $outputs.GetEnumerator()) {
  $path = Join-Path $dataRoot $entry.Key
  if ($Check) {
    if (!(Test-Path -LiteralPath $path) -or [IO.File]::ReadAllText($path).Replace("`r`n", "`n") -cne $entry.Value) { throw "Fichier à régénérer avec scripts/sync-categories.ps1 : $path" }
  } else { [IO.File]::WriteAllText($path, $entry.Value, [Text.UTF8Encoding]::new($false)) }
}
Write-Output "5 catégories de 75 questions validées ; $($bundle.questions.Count) questions nouvelles. Fichiers synchronisés."
